Repository SkyAPM/SkyAPM-dotnet, pull requests merged in 2018-05, with the labels that each got.

#37 Add supports for EntityFrameworkCore
  skywalking-csharp.sln
  src/SkyWalking.Diagnostics.EntityFrameworkCore/EntityFrameworkCoreDiagnosticProcessor.cs
  src/SkyWalking.Diagnostics.EntityFrameworkCore/SkyWalking.Diagnostics.EntityFrameworkCore.csproj
  src/SkyWalking.Diagnostics.EntityFrameworkCore/SkyWalkingBuilderExtensions.cs
  test/SkyWalking.Diagnostics.EntityFrameworkCore.Tests/EFCoreDiagnosticProcessorTests.cs
  test/SkyWalking.Diagnostics.EntityFrameworkCore.Tests/Fakes/Fake.DbContext.cs
  test/SkyWalking.Diagnostics.EntityFrameworkCore.Tests/Fakes/Fake.IgnoreTracerContextListener.cs
  test/SkyWalking.Diagnostics.EntityFrameworkCore.Tests/Fakes/Fake.User.cs
  test/SkyWalking.Diagnostics.EntityFrameworkCore.Tests/SkyWalking.Diagnostics.EntityFrameworkCore.Tests.csproj
Labels: enhancement

#38 Fixed parameter bind bug
  src/SkyWalking.Diagnostics.EntityFrameworkCore/EntityFrameworkCoreDiagnosticProcessor.cs
Labels: bug

#39 Support corefx built-in SqlClient
  skywalking-csharp.sln
  src/SkyWalking.AspNetCore/Extensions/ServiceCollectionExtensions.cs
  src/SkyWalking.AspNetCore/SkyWalking.AspNetCore.csproj
  src/SkyWalking.Diagnostics.EntityFrameworkCore/EntityFrameworkCoreDiagnosticProcessor.cs
  src/SkyWalking.Diagnostics.EntityFrameworkCore/SkyWalking.Diagnostics.EntityFrameworkCore.csproj
  src/SkyWalking.Diagnostics.SqlClient/SkyWalking.Diagnostics.SqlClient.csproj
  src/SkyWalking.Diagnostics.SqlClient/SkyWalkingBuilderExtensions.cs
  src/SkyWalking.Diagnostics.SqlClient/SqlClientDiagnosticProcessor.cs
  src/SkyWalking.Diagnostics.SqlClient/SqlClientDiagnosticStrings.cs
Labels: enhancement

#42 Record request logs and exception stack
  sample/SkyWalking.Sample.Backend/Controllers/ErrorsController.cs
  src/SkyWalking.AspNetCore/Diagnostics/HostingDiagnosticProcessor.cs
  src/SkyWalking.AspNetCore/Diagnostics/HttpContextDiagnosticStrings.cs
Labels: enhancement

#44 [Refactor] Remove Nito.AsyncEx.Coordination package and add internal AsyncLock
  src/SkyWalking.Core/Remote/GrpcConnectionManager.cs
  src/SkyWalking.Core/SkyWalking.Core.csproj
  src/SkyWalking.Core/Utils/AsyncLock.cs
Labels: enhancement

#45 Fix: Register application/applicationInstance service return null
  sample/SkyWalking.Sample.Frontend/appsettings.Development.json
  sample/SkyWalking.Sample.Frontend/appsettings.json
  src/SkyWalking.AspNetCore/Diagnostics/HostingDiagnosticProcessor.cs
  src/SkyWalking.AspNetCore/SkyWalkingHostedService.cs
  src/SkyWalking.Core/Context/Trace/TraceSegment.cs
  src/SkyWalking.Core/Remote/GrpcApplicationService.cs
  src/SkyWalking.Core/Remote/GrpcConnection.cs
  src/SkyWalking.Core/Remote/GrpcConnectionManager.cs
  src/SkyWalking.Core/Remote/GrpcConnectionService.cs
  src/SkyWalking.Core/Remote/GrpcHeartbeatService.cs
Labels: bug

#47 fix Device not configured
  src/SkyWalking.Core/Remote/GrpcApplicationService.cs
Labels: bug

#48 Update README and Supported-List
  README.md
  docs/Supported-list.md
Labels: document
