Repository SkyAPM/SkyAPM-dotnet, pull requests merged in 2019-02, with the labels that each got.

#137 Fix Asp.Net Core package version conflicts
  sample/SkyWalking.Sample.Backend/SkyWalking.Sample.Backend.csproj
  src/SkyWalking.Abstractions/Config/InstrumentationConfig.cs
  src/SkyWalking.Agent.AspNetCore/SkyWalking.Agent.AspNetCore.csproj
  src/SkyWalking.Diagnostics.AspNetCore/HostingDiagnosticProcessor.cs
  src/SkyWalking.Diagnostics.AspNetCore/SkyWalking.Diagnostics.AspNetCore.csproj
  src/SkyWalking.Diagnostics.CAP/SkyWalking.Diagnostics.CAP.csproj
  src/SkyWalking.Diagnostics.EntityFrameworkCore.Npgsql/NpgsqlEFCoreSpanMetadataProvider.cs
  src/SkyWalking.Diagnostics.EntityFrameworkCore.Npgsql/SkyWalking.Diagnostics.EntityFrameworkCore.Npgsql.csproj
  src/SkyWalking.Diagnostics.EntityFrameworkCore.Pomelo.MySql/MySqlEFCoreSpanMetadataProvider.cs
  src/SkyWalking.Diagnostics.EntityFrameworkCore.Pomelo.MySql/SkyWalking.Diagnostics.EntityFrameworkCore.Pomelo.MySql.csproj
  src/SkyWalking.Diagnostics.EntityFrameworkCore.Sqlite/SkyWalking.Diagnostics.EntityFrameworkCore.Sqlite.csproj
  src/SkyWalking.Diagnostics.EntityFrameworkCore.Sqlite/SqliteEFCoreSpanMetadataProvider.cs
  src/SkyWalking.Diagnostics.EntityFrameworkCore/SkyWalking.Diagnostics.EntityFrameworkCore.csproj
  src/SkyWalking.Diagnostics.MySqlData/SkyWalking.Diagnostics.MySqlData.csproj
  src/SkyWalking.Diagnostics.SqlClient/SkyWalking.Diagnostics.SqlClient.csproj
  src/SkyWalking.Utilities.Configuration/SkyWalking.Utilities.Configuration.csproj
  src/SkyWalking.Utilities.DependencyInjection/SkyWalking.Utilities.DependencyInjection.csproj
  src/SkyWalking.Utilities.Logging/DefaultLoggerFactory.cs
  src/SkyWalking.Utilities.Logging/SkyWalking.Utilities.Logging.csproj
Labels: bug, enhancement

#140 Re-implementation language-agent-protocol V5
  src/SkyWalking.Abstractions/Context/Trace/ITraceSegment.cs
  src/SkyWalking.Abstractions/Context/Trace/ITraceSegmentRef.cs
  src/SkyWalking.Abstractions/ISkyWalkingClient.cs
  src/SkyWalking.Abstractions/Transport/ISegmentDispatcher.cs
  src/SkyWalking.Abstractions/Transport/ISegmentReporter.cs
  src/SkyWalking.Abstractions/Transport/SegmentRequest.cs
  src/SkyWalking.Abstractions/Transport/V5/ISkyWalkingClientV5.cs
  src/SkyWalking.Agent.AspNetCore/Extensions/ServiceCollectionExtensions.cs
  src/SkyWalking.AspNet/Extensions/ServiceCollectionExtensions.cs
  src/SkyWalking.Core/Context/Trace/TraceSegment.cs
  src/SkyWalking.Core/Context/Trace/TraceSegmentRef.cs
  src/SkyWalking.Core/Service/PingService.cs
  src/SkyWalking.Core/Service/RegisterService.cs
  src/SkyWalking.Core/Service/SegmentReportService.cs
  src/SkyWalking.Core/Service/ServiceDiscoveryV5Service.cs
  src/SkyWalking.Core/SkyWalkingAgentStartup.cs
  src/SkyWalking.Core/Transport/AsyncQueueSegmentDispatcher.cs
  src/SkyWalking.Transport.Grpc/ConnectionManager.cs
  src/SkyWalking.Transport.Grpc/GrpcConfig.cs
  src/SkyWalking.Transport.Grpc/SegmentReporter.cs
  src/SkyWalking.Transport.Grpc/Utils/SegmentV5Helpers.cs
  src/SkyWalking.Transport.Grpc/Utils/SegmentV6Helpers.cs
  src/SkyWalking.Transport.Grpc/V5/SegmentReporter.cs
  src/SkyWalking.Transport.Grpc/V5/SkyWalkingClientV5.cs
  src/SkyWalking.Transport.Grpc/V6/SegmentReporter.cs
  src/SkyWalking.Utilities.Configuration/ConfigurationBuilderExtensions.cs
  src/SkyWalking.Utilities.Logging/DefaultLoggerFactory.cs
Labels: enhancement

#142 Remove the Apache SkyWalking logo first
  README.md
Labels: document

#151 Add `IAdditionalConfigurationSource` to load the agent-config from th…
  src/SkyApm.Agent.AspNet/Extensions/ServiceCollectionExtensions.cs
  src/SkyApm.Agent.AspNetCore/Extensions/ServiceCollectionExtensions.cs
  src/SkyApm.Utilities.Configuration/ConfigAccessor.cs
  src/SkyApm.Utilities.Configuration/ConfigurationFactory.cs
  src/SkyApm.Utilities.Configuration/IAdditionalConfigurationSource.cs
  src/SkyApm.Utilities.Configuration/IConfigurationFactory.cs
Labels: enhancement

#155 Upgrade bootstrap to version 3.4.1
  build/version.props
  sample/SkyApm.Sample.AspNet/packages.config
Labels: bug
